from typing import Any
import random
from models.game.entities.base_entity import BaseEntity
from models.game.skills.base_skill import BaseSkill
from models.game.effects.handlers.effect_handlers import EFFECT_HANDLERS
from models.game.party import Party

# TODO: add custom errors

class SkillUseService:
    """Service for handling skill usage and related logic."""
    # Context dictionary for Effects
    # This will be passed to the effect handlers to allow them to modify the behavior of the entity based on the effect
    @staticmethod
    def make_effect_context() -> dict[str, Any]:
        return {
            # Damage Logic
            "skip_turn": False,                 # Used for effects like Stun that skip the entity's turn
            "silenced": False,                  # Used for effects like Silence that prevent the entity from using skills
            "muted": False,                     # Used for effects like Mute that prevent the entity from using magical skills
            "rooted": False,                    # Used for effects like Root that prevent the entity from moving
            "confused": False,                  # Used for effects like Confusion that may cause the entity to hurt itself
            "self_hit_chance": 0.0,                # Used for effects like Confusion that may cause the entity to hurt itself - represents the chance to self-hit each turn
            
            # Action Flow
            "damage_blocked": False,            # Used for effects like Shield that block incoming damage
            "block_dot": False,                 # Used for effects like Endure that block damage over time effects

            # Extra Actions
            "extra_attacks": 0,                 # Used for effects like Double Attack that allow the entity to attack multiple times
            "extra_attack_multiplier" : 1.0,    # Used for effects that modify the power of extra attacks (e.g. Double Attack with a stat magnifier)
            
            # Targeting Logic
            "force_target": None,              # Used for effects that force the entity to target a specific enemy (e.g. Taunt)
        }
    
    # This helper method applies all complex effects for an entity and returns the context that will be used for the entity's turn
    # This makes sure that a new context is generated for each turn and that all effects are applied in a consistent way
    @staticmethod
    def apply_effect_handlers(entity: BaseEntity) -> dict[str, Any]:
        context = SkillUseService.make_effect_context()
        for effect in entity.active_effects:
            handler = EFFECT_HANDLERS.get(effect.effect_name)
            if handler:
                handler(entity, effect, context)
        return context

    @staticmethod
    def _execute_skill_with_power_multiplier(
        user: BaseEntity,
        skill: BaseSkill,
        target: BaseEntity,
        multiplier: float,
    ) -> None:
        """Helper method to execute a skill with a modified power multiplier."""
        # Store original power to restore after use
        original_power = skill.power
        try:
            # Temporarily modify the skill's power for this attack
            skill.power = int(skill.power * multiplier)
            # Use the skill with the modified power
            skill.use(user, target)
        finally:
            # Restore the original power of the skill
            skill.power = original_power

    # This method takes the context generated by both apply_effect_handlers and make_effect_context and applies it to the entity's turn, modifying the behavior of the entity based on the active effects
    @staticmethod
    def use_skill(
        user: BaseEntity, 
        skill: BaseSkill, 
        target: BaseEntity,
        target_party: Party | None = None
    ) -> dict[str, Any]:
        context = SkillUseService.apply_effect_handlers(user)

        # ----------------------- SKIP TURN -----------------------
        # -------- STUN -> Skip Turn --------
        if context["skip_turn"]:
            # Return a dictionary that flags turn status
            return { "status": "skip", "reason": "stunned"}
        # -------- CONFUSED -> Skips Turn if Successful --------
        if context["confused"] and random.random() < context["self_hit_chance"]:
            self_damage = max(
                1,
                int(user.max_health * 0.08) +
                max(0, int(user.current_physical_attack * 0.2) - 
                    int(user.current_physical_defense * 0.2))
            )
            user.take_damage(self_damage)
            # Entity skips their turn if hit with confusion.
            return {
                "status": "skip",
                "reason": "confused",
                "message": f"{user.title} is hit with confusion. {user.title} hurt themself with {self_damage} points."
            }

        # ----------------------- VALIDATION  -----------------------
        # --------- SILENCE/ROOT/MUTED -> Prevents Certain Actions --------
        # Validation for silence/mute/root/etc effects that prevent the entity from using certain types of skills
        # If the entity uses a skill but is silenced and cannot use skills
        if context["silenced"] and skill is not None: 
            return {
                "status": "invalid",
                "reason": "silenced",
                "error": "Invalid Action Error",
                "message": "Invalid option, you cannot use skills"
            }
        # ----- TODO: Update skill types to differentiate between physical and magical skills so we can properly block physical skills when rooted without affecting magical skills
        if context["rooted"] and skill is not None and skill.skill_type == SkillType.OFFENSIVE:  # Assuming that physical skills are categorized as offensive
            return {
                "status": "invalid",
                "reason": "rooted",
                "error": "Invalid Action Error",
                "message": "Invalid option, you cannot use physical skills"
            }
        if context["muted"] and skill is not None and skill.skill_type == SkillType.OFFENSIVE:  # Assuming that magical skills are categorized as offensive
            return {
                "status": "invalid",
                "reason": "muted",
                "error": "Invalid Action Error",
                "message": "Invalid option, you cannot use magical skills"
            }
        # -------- TAUNT -> Enforces Targeting --------
        # Check if any of the target's party members have Taunt active, and if so, force the user to target the taunting entity instead of their intended target
        # Check context of target's party members for Taunt effect
        if target_party: 
            taunt_targets = [
                member for member in target_party.get_alive_members()
                if any(e.effect_name == StatusEffects.TAUNT.value for e in member.active_effects)
            ]
            if taunt_targets and target not in taunt_targets:
                return {
                    "status": "invalid",
                    "reason": "taunt",
                    "error": "Invalid Targeting Error",
                    "message": "Please choose a correct target",
                    "valid_targets": [t.id for t in taunt_targets]
                }

        # ----------------------- DAMAGE LOGIC -----------------------
        # -------- SHIELD/ENDURE -> Blocks Incoming Damage --------
        # TODO: implement shield and endure logic in the damage calculation and application process, using the context to determine whether to block damage or not 


        # -------- DOUBLE ATTACK -> Allows for Extra Attacks --------
        if context["extra_attacks"] > 0:
            # Handle extra attacks (e.g. from Double Attack)
            for _ in range(context["extra_attacks"]):
                SkillUseService._execute_skill_with_power_multiplier(
                    skill=skill, 
                    user=user, 
                    target=target, 
                    multiplier=context["extra_attack_multiplier"]
                )
                total_hits += 1
            return {
                "status": "success",
                "reason": "extra_attacks",
                "hits": total_hits,
                "message": f"{user.title} used {skill.name} and hit {target.title} {total_hits} times."
            }